name: C# Integration Tests

on:
  push:
    branches: [ main, develop ]
    paths: [ 'examples/csharp-mssql-integration/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'examples/csharp-mssql-integration/**' ]

defaults:
  run:
    working-directory: ./examples/csharp-mssql-integration

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
      
    - name: Run integration tests
      run: dotnet test --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: examples/csharp-mssql-integration/tests/**/TestResults/*.trx